# Generated by Django 6.0.2 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('earliest_start', models.PositiveIntegerField(blank=True, null=True)),
                ('earliest_finish', models.PositiveIntegerField(blank=True, null=True)),
                ('latest_start', models.PositiveIntegerField(blank=True, null=True)),
                ('latest_finish', models.PositiveIntegerField(blank=True, null=True)),
                ('slack', models.IntegerField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['earliest_start', 'name'],
            },
        ),
    ]
