# Generated by Django 6.0.2 on 2026-03-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('predecessor', 'successor')},
        ),
    ]
